// Mozilla Public License 2.0, and LGPL License.

// WARNING: This file has automatically been generated on Sat, 09 Jul 2022 13:09:20 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void go_plc_tag_create_ex_callback_6ee5b39c(int tag_id, int event, int status, void* userdata) {
	createExCallback6EE5B39C(tag_id, event, status, userdata);
}

void go_plc_tag_register_ex_callback_858e2960(int tag_id, int event, int status, void* userdata) {
	registerExCallback858E2960(tag_id, event, status, userdata);
}

void go_plc_tag_register_logger_callback_63095d5a(int tag_id, int debug_level, char* message) {
	registerLoggerCallback63095D5A(tag_id, debug_level, message);
}

