// Mozilla Public License 2.0, and LGPL License.

// WARNING: This file has automatically been generated on Sat, 09 Jul 2022 00:13:50 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "libplctag.h"
#include "callbacks.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// go_plc_tag_create_ex_callback_6ee5b39c is a proxy for callback go_plc_tag_create_ex_callback.
void go_plc_tag_create_ex_callback_6ee5b39c(int tag_id, int event, int status, void* userdata);

// go_plc_tag_register_ex_callback_858e2960 is a proxy for callback go_plc_tag_register_ex_callback.
void go_plc_tag_register_ex_callback_858e2960(int tag_id, int event, int status, void* userdata);

// go_plc_tag_register_logger_callback_63095d5a is a proxy for callback go_plc_tag_register_logger_callback.
void go_plc_tag_register_logger_callback_63095d5a(int tag_id, int debug_level, char* message);

