// Mozilla Public License 2.0, and LGPL License.

// WARNING: This file has automatically been generated on Sat, 09 Jul 2022 00:13:50 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go package plctag, a wrapper for libplctag c library
*/
package plctag
