// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 08 Jul 2022 14:56:03 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package goplctag a wrapper for libplctag c library
*/
package callbacks
