// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jul 2022 17:58:10 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "libplctag.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

