// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 07 Jul 2022 16:20:06 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package goplctag a wrapper for libplctag c library
*/
package goplctag
