// Mozilla Public License 2.0, and LGPL License.

// WARNING: This file has automatically been generated on Sat, 09 Jul 2022 16:25:18 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Go package goplctag, a wrapper for libplctag c library
*/
package goplctag
