// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 06 Jul 2022 17:58:10 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package goplctag a wrapper for libplctag c library
*/
package goplctag
